# Generated by Django 5.1.5 on 2025-03-26 23:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='level',
            name='level_class',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='tutor',
            name='user_pic',
            field=models.ImageField(blank=True, default='defaultProfilePic.jpeg', null=True, upload_to=''),
        ),
        migrations.CreateModel(
            name='Tutee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('joined', models.DateTimeField(auto_now_add=True)),
                ('phone', models.IntegerField(null=True)),
                ('level', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='backend.level')),
                ('tutor_subject', models.ManyToManyField(to='backend.tutorsubject')),
            ],
        ),
        migrations.CreateModel(
            name='TuteeHours',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hours', models.IntegerField()),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.subject')),
                ('tutee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tutee')),
            ],
        ),
    ]
