# Generated by Django 5.1.5 on 2025-03-27 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0002_level_level_class_tutor_user_tutor_user_pic_tutee_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tuteehours',
            old_name='tutee',
            new_name='name',
        ),
    ]
