# Generated by Django 5.1.5 on 2025-05-05 02:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0003_rename_tutee_tuteehours_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='tuteehours',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Paid', 'Paid'), ('Not Paid', 'Not Paid')], default='Not Paid', max_length=10)),
                ('month', models.DateField()),
                ('tutor_subject', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backend.tutorsubject')),
            ],
            options={
                'unique_together': {('tutor_subject', 'month')},
            },
        ),
    ]
